"""Application port for read-only Catalog queries."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol


class CatalogQueryRepository(Protocol):
    """Infrastructure port used by the Platform Catalog application service."""

    @property
    def catalog_revision(self) -> str: ...

    def list_spaces(self) -> list[Mapping[str, Any]]: ...

    def list_assets(self, *, space_id: str | None = None) -> list[Mapping[str, Any]]: ...

    def list_collections(self, *, space_id: str | None = None) -> list[Mapping[str, Any]]: ...

    def list_connectors(self, *, space_id: str) -> list[Mapping[str, Any]]: ...

    def list_source_items(self, *, space_id: str, connector_id: str | None = None) -> list[Mapping[str, Any]]: ...

    def list_connector_authorizations(self, *, space_id: str) -> list[Mapping[str, Any]]: ...

    def search_assets(self, *, text: str, space_id: str | None, limit: int) -> list[Mapping[str, Any]]: ...

    def get_asset(self, *, asset_id: str) -> Mapping[str, Any] | None: ...

    def get_query_result(self, *, query_result_id: str) -> Mapping[str, Any] | None: ...

    def get_job(self, *, job_id: str) -> Mapping[str, Any] | None: ...

    def get_structured_asset(self, *, asset_id: str) -> Mapping[str, Any] | None: ...
