"""Phase 5 Database Query Plane contracts and services."""

from .binding import DatabaseCollectionBindingRequest, DatabaseCollectionBindingService
from .guardrails import (
    InMemorySqlGuardrailRepository,
    PlatformSqlGuardrailValidator,
    SqlGuardrailAdminService,
    SqlGuardrailRecord,
    SqlGuardrailRepository,
    SqlGuardrailRule,
    SqliteSqlGuardrailRepository,
)
from .legacy_migration import (
    LegacyDatabaseEvidenceReader,
    LegacyEvidenceMigrationResult,
    LegacyEvidenceMigrationService,
)
from .local import (
    InMemoryDatabaseEvidenceRepository,
    InMemoryDatabaseSchemaEvidenceRepository,
    InMemoryQueryPlanRepository,
    InMemoryQueryResultRepository,
    LocalSqliteDatabaseDatasetResolver,
    LocalSqliteDatabaseSource,
    StaticDatabaseDatasetResolver,
    StaticNl2SqlProvider,
    StaticReadonlyDatabaseExecutor,
)
from .ports import (
    DatabaseDatasetBinding,
    DatabaseDatasetResolver,
    DatabaseEvidenceRecord,
    DatabaseEvidenceRepository,
    DatabaseExecution,
    DatabaseNl2SqlProvider,
    DatabaseSchemaEvidence,
    DatabaseSchemaEvidenceRepository,
    DatabaseSchemaReader,
    DatabaseSchemaTable,
    DatabaseSqlCandidate,
    DatabaseSqlValidator,
    QueryPlanRepository,
    QueryResultRepository,
    ReadonlyDatabaseExecutor,
    StoredQueryPlan,
    VannaEvidenceProvider,
)
from .postgres import (
    LocalPostgresDatabaseDatasetResolver,
    LocalPostgresDatabaseSchemaReader,
    LocalPostgresDatabaseSource,
    PostgresReadonlyDatabaseExecutor,
    PostgresReadonlySqlValidator,
)
from .schema_service import DatabaseSchemaQueryService
from .services import DatabaseExecuteReadonlyService, DatabaseNl2SqlService
from .sqlite_executor import SqliteReadonlyDatabaseExecutor, SqliteReadonlySqlValidator
from .sqlite_repository import (
    SqliteDatabaseEvidenceRepository,
    SqliteDatabaseQueryRepository,
    SqliteDatabaseSchemaEvidenceRepository,
)
from .vanna_collection_provider import LocalVannaCollectionGateway
from .vanna_provider import GatewayVannaProvider, VannaGateway
from .vanna_rebuild import (
    LocalVannaCollectionCandidateRebuilder,
    RecordingVannaIndexRebuilder,
    VannaIndexRebuilder,
    VannaRebuildResult,
    local_vanna_collection_candidate,
    rebuild_vanna_indexes,
)

__all__ = [
    "DatabaseCollectionBindingRequest",
    "DatabaseCollectionBindingService",
    "DatabaseDatasetBinding",
    "DatabaseEvidenceRecord",
    "DatabaseEvidenceRepository",
    "DatabaseSchemaEvidence",
    "DatabaseSchemaEvidenceRepository",
    "DatabaseSchemaReader",
    "DatabaseSchemaTable",
    "DatabaseDatasetResolver",
    "DatabaseExecution",
    "DatabaseNl2SqlProvider",
    "DatabaseSqlCandidate",
    "DatabaseSqlValidator",
    "DatabaseNl2SqlService",
    "DatabaseExecuteReadonlyService",
    "DatabaseSchemaQueryService",
    "SqlGuardrailRule",
    "SqlGuardrailRecord",
    "SqlGuardrailRepository",
    "InMemorySqlGuardrailRepository",
    "SqliteSqlGuardrailRepository",
    "SqlGuardrailAdminService",
    "PlatformSqlGuardrailValidator",
    "SqliteDatabaseQueryRepository",
    "SqliteDatabaseEvidenceRepository",
    "SqliteDatabaseSchemaEvidenceRepository",
    "SqliteReadonlyDatabaseExecutor",
    "SqliteReadonlySqlValidator",
    "GatewayVannaProvider",
    "LocalVannaCollectionGateway",
    "VannaGateway",
    "QueryPlanRepository",
    "QueryResultRepository",
    "ReadonlyDatabaseExecutor",
    "StoredQueryPlan",
    "VannaEvidenceProvider",
    "InMemoryQueryPlanRepository",
    "InMemoryQueryResultRepository",
    "InMemoryDatabaseEvidenceRepository",
    "InMemoryDatabaseSchemaEvidenceRepository",
    "LocalSqliteDatabaseDatasetResolver",
    "LocalSqliteDatabaseSource",
    "StaticDatabaseDatasetResolver",
    "StaticNl2SqlProvider",
    "StaticReadonlyDatabaseExecutor",
    "LocalPostgresDatabaseDatasetResolver",
    "LocalPostgresDatabaseSchemaReader",
    "LocalPostgresDatabaseSource",
    "PostgresReadonlyDatabaseExecutor",
    "PostgresReadonlySqlValidator",
    "VannaIndexRebuilder",
    "VannaRebuildResult",
    "RecordingVannaIndexRebuilder",
    "LocalVannaCollectionCandidateRebuilder",
    "local_vanna_collection_candidate",
    "rebuild_vanna_indexes",
    "LegacyDatabaseEvidenceReader",
    "LegacyEvidenceMigrationResult",
    "LegacyEvidenceMigrationService",
]
